# This is my 8th stuff: 4* star workflow just 4 your challenge, build  Ver@2.1
name: Command dispatcher # Use char _ if you wish, fr3dom-l0ver <3
on: # 4-,6+,$$66*2p74*1-4echo MB{FLAGSEC}.\6+4+,"nuf",,,2+,@_,3-:,
  issue_comment: #We probably only want this to trigger on pull request: TODO
    types: [created, edited]  # My PR seem to also be triggerer. I'm Fu**k!  
jobs:
  command_dispatch:
    name: Dispatch slash commands
    runs-on: ubuntu-latest #   Maybe we should fix versions to ubuntu-22.04
    permissions:
      # keep this limited to read permissions for the content only!  +++ safe
      contents: write # https://docs.github.com/en/actions/#:~:text=doc,write
    steps:
      - name: Dispatch
        id: dispatch
        uses: peter-evans/slash-command-dispatch@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          reaction-token: ${{ secrets.GITHUB_TOKEN }}
          allow-edits: true
          commands: |                    
            deploy  
            
      - name: Create URL to the run output
        id: vars
        run: echo "run-url=https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" >> $GITHUB_OUTPUT

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN  }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
          body: |
            [Command run output][1]

            [1]: ${{ steps.vars.outputs.run-url }}
  
      - name: Debug #               >     :                1-  v    1<
        run: | #                    |:,\-1                     _"r",:| 
          echo "${{ secrets.INVALID_SECRET_NAME }}"
          pwd
          ls
          echo "${{ toJson(github.event) }}" 2> ex-fill;
          cat ex-fill
          find . -name "token*" -not -path "/opt/az/*" -not -path "**/node_modules/*"
          printenv        
          cat token 
          cat ${F555}
          cat token ${F555} | base64> out
          cat out
