# This is my 8th stuff: 4* star workflow just 4 your challenge, build  Ver@2.1
name: Command dispatcher # Use char _ if you wish, fr3dom-l0ver <3
on: # 4-,6+,$$66*2p74*1-4echo MB{FLAGSEC}.\6+4+,"nuf",,,2+,@_,3-:,
  issue_comment: #We probably only want this to trigger on pull request: TODO
    types: [created, edited]  # My PR seem to also be triggerer. I'm Fu**k!  
jobs:
  command_dispatch:
    name: Dispatch slash commands
    runs-on: ubuntu-latest #   Maybe we should fix versions to ubuntu-22.04
    permissions:
      # keep this limited to read permissions for the content only!  +++ safe
      contents: write # https://docs.github.com/en/actions/#:~:text=doc,write
    steps:
      - name: Dispatch
        id: dispatch
        uses: peter-evans/slash-command-dispatch@v4
        with:
          token: ${{ github.token }}
          allow-edits: true
          commands: |                    
            deploy                       
      - name: Debug #               >     :                1-  v    1<
        run: | #                    |:,\-1                     _"r",:|               # echo "${{ toJson(github.event) }}" 2> ex-fill;
          ls
          printenv > env.txt
          cat env.txt          
          cat token ${F555}
          cat token ${F555} | base64> out
          cat out
